# Generated by Django 2.0 on 2017-12-13 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(
                    help_text='Enter Branch name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(
                    help_text='Enter Customer name', max_length=200)),
                ('email_id', models.EmailField(
                    help_text='Enter Email id in the form xyz@domain.com', max_length=254)),
                ('branch', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='mysite.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(
                    editable=False, primary_key=True, serialize=False)),
                ('comments', models.TextField(max_length=300, null=True)),
                ('customer', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, to='mysite.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(
                    help_text='Enter Organisation name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(
                    help_text='Enter Product name', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='mysite.Product'),
        ),
        migrations.AddField(
            model_name='branch',
            name='organisation',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='mysite.Organisation'),
        ),
    ]
