# Generated by Django 2.0 on 2017-12-12 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('name', models.CharField(help_text='Enter Branch name', max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(help_text='Enter Customer  name', max_length=200)),
                ('email_id', models.EmailField(help_text='Enter Email id in the form xyz@domain.com', max_length=254, primary_key=True, serialize=False)),
                ('branch_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('comments', models.TextField(max_length=300, null=True)),
                ('cust_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('name', models.CharField(help_text='Enter Organisation name', max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Product  name', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.Product'),
        ),
        migrations.AddField(
            model_name='branch',
            name='org_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mysite.Organisation'),
        ),
    ]
